### Get all ToMakes
GET http://localhost:8080/v1 HTTP/1.1

### Get ToMake by ID
GET http://localhost:8080/v1/1 HTTP/1.1

### Post new ToMake
POST  http://localhost:8080/v1 HTTP/1.1
Content-Type: application/json

{
    "name": "toMake item",
    "description": "New item desc"
}

### Delete ToMake by ID
DELETE   http://localhost:8080/v1/4 HTTP/1.1


### Update ToMake by ID
PUT  http://localhost:8080/v1/5 HTTP/1.1
Content-Type: application/json
{
    "name": "toMake item",
    "description": "New item desc"
}








